
// verbs.js

const verbs = {
  "Be": { base: "be", past: "was/were", pastParticiple: "been", meaning: "होना" },
  "Have": { base: "have", past: "had", pastParticiple: "had", meaning: "होना, पास होना" },
  "Do": { base: "do", past: "did", pastParticiple: "done", meaning: "करना" },
  "Say": { base: "say", past: "said", pastParticiple: "said", meaning: "कहना" },
  "Go": { base: "go", past: "went", pastParticiple: "gone", meaning: "जाना" },
  "Get": { base: "get", past: "got", pastParticiple: "gotten/got", meaning: "प्राप्त करना" },
  "Make": { base: "make", past: "made", pastParticiple: "made", meaning: "बनाना" },
  "Know": { base: "know", past: "knew", pastParticiple: "known", meaning: "जानना" },
  "Take": { base: "take", past: "took", pastParticiple: "taken", meaning: "लेना" },
  "See": { base: "see", past: "saw", pastParticiple: "seen", meaning: "देखना" },
  "Come": { base: "come", past: "came", pastParticiple: "come", meaning: "आना" },
  "Think": { base: "think", past: "thought", pastParticiple: "thought", meaning: "सोचना" },
  "Look": { base: "look", past: "looked", pastParticiple: "looked", meaning: "देखना" },
  "Want": { base: "want", past: "wanted", pastParticiple: "wanted", meaning: "चाहना" },
  "Give": { base: "give", past: "gave", pastParticiple: "given", meaning: "देना" },
  "Use": { base: "use", past: "used", pastParticiple: "used", meaning: "उपयोग करना" },
  "Find": { base: "find", past: "found", pastParticiple: "found", meaning: "ढूंढना" },
  "Tell": { base: "tell", past: "told", pastParticiple: "told", meaning: "बताना" },
  "Ask": { base: "ask", past: "asked", pastParticiple: "asked", meaning: "पूछना" },
  "Work": { base: "work", past: "worked", pastParticiple: "worked", meaning: "काम करना" },
  "Seem": { base: "seem", past: "seemed", pastParticiple: "seemed", meaning: "प्रतीत होना" },
  "Feel": { base: "feel", past: "felt", pastParticiple: "felt", meaning: "महसूस करना" },
  "Try": { base: "try", past: "tried", pastParticiple: "tried", meaning: "प्रयास करना" },
  "Leave": { base: "leave", past: "left", pastParticiple: "left", meaning: "छोड़ना" },
  "Call": { base: "call", past: "called", pastParticiple: "called", meaning: "बुलाना" },
  "Need": { base: "need", past: "needed", pastParticiple: "needed", meaning: "जरूरत होना" },
  "Become": { base: "become", past: "became", pastParticiple: "become", meaning: "बनना" },
  "Show": { base: "show", past: "showed", pastParticiple: "shown", meaning: "दिखाना" },
  "Hear": { base: "hear", past: "heard", pastParticiple: "heard", meaning: "सुनना" },
  "Play": { base: "play", past: "played", pastParticiple: "played", meaning: "खेलना" },
  "Run": { base: "run", past: "ran", pastParticiple: "run", meaning: "दौड़ना" },
  "Move": { base: "move", past: "moved", pastParticiple: "moved", meaning: "हिलाना" },
  "Like": { base: "like", past: "liked", pastParticiple: "liked", meaning: "पसंद करना" },
  "Live": { base: "live", past: "lived", pastParticiple: "lived", meaning: "जीना" },
  "Believe": { base: "believe", past: "believed", pastParticiple: "believed", meaning: "विश्वास करना" },
  "Hold": { base: "hold", past: "held", pastParticiple: "held", meaning: "पकड़ना" },
  "Bring": { base: "bring", past: "brought", pastParticiple: "brought", meaning: "लाना" },
  "Happen": { base: "happen", past: "happened", pastParticiple: "happened", meaning: "घटित होना" },
  "Write": { base: "write", past: "wrote", pastParticiple: "written", meaning: "लिखना" },
  "Provide": { base: "provide", past: "provided", pastParticiple: "provided", meaning: "प्रदान करना" },
  "Sit": { base: "sit", past: "sat", pastParticiple: "sat", meaning: "बैठना" },
  "Stand": { base: "stand", past: "stood", pastParticiple: "stood", meaning: "खड़ा होना" },
  "Lose": { base: "lose", past: "lost", pastParticiple: "lost", meaning: "खोना" },
  "Pay": { base: "pay", past: "paid", pastParticiple: "paid", meaning: "भुगतान करना" },
  "Meet": { base: "meet", past: "met", pastParticiple: "met", meaning: "मिलना" },
  "Include": { base: "include", past: "included", pastParticiple: "included", meaning: "शामिल करना" },
  "Continue": { base: "continue", past: "continued", pastParticiple: "continued", meaning: "जारी रखना" },
  "Set": { base: "set", past: "set", pastParticiple: "set", meaning: "सेट करना" },
  "Learn": { base: "learn", past: "learned/learnt", pastParticiple: "learned/learnt", meaning: "सीखना" },
  "Change": { base: "change", past: "changed", pastParticiple: "changed", meaning: "बदलना" },
  "Lead": { base: "lead", past: "led", pastParticiple: "led", meaning: "नेतृत्व करना" },
  "Understand": { base: "understand", past: "understood", pastParticiple: "understood", meaning: "समझना" },
  "Watch": { base: "watch", past: "watched", pastParticiple: "watched", meaning: "देखना" },
  "Follow": { base: "follow", past: "followed", pastParticiple: "followed", meaning: "अनुसरण करना" },
  "Stop": { base: "stop", past: "stopped", pastParticiple: "stopped", meaning: "रुकना" },
  "Create": { base: "create", past: "created", pastParticiple: "created", meaning: "बनाना" },
  "Speak": { base: "speak", past: "spoke", pastParticiple: "spoken", meaning: "बोलना" },
  "Read": { base: "read", past: "read", pastParticiple: "read", meaning: "पढ़ना" },
  "Allow": { base: "allow", past: "allowed", pastParticiple: "allowed", meaning: "अनुमति देना" },
  "Add": { base: "add", past: "added", pastParticiple: "added", meaning: "जोड़ना" },
  "Spend": { base: "spend", past: "spent", pastParticiple: "spent", meaning: "खर्च करना" },
  "Grow": { base: "grow", past: "grew", pastParticiple: "grown", meaning: "बढ़ना" },
  "Open": { base: "open", past: "opened", pastParticiple: "opened", meaning: "खोलना" },
  "Walk": { base: "walk", past: "walked", pastParticiple: "walked", meaning: "चलना" },
  "Win": { base: "win", past: "won", pastParticiple: "won", meaning: "जीतना" },
  "Offer": { base: "offer", past: "offered", pastParticiple: "offered", meaning: "प्रस्ताव देना" },
  "Remember": { base: "remember", past: "remembered", pastParticiple: "remembered", meaning: "याद रखना" },
  "Love": { base: "love", past: "loved", pastParticiple: "loved", meaning: "प्यार करना" },
  "Consider": { base: "consider", past: "considered", pastParticiple: "considered", meaning: "विचार करना" },
  "Appear": { base: "appear", past: "appeared", pastParticiple: "appeared", meaning: "प्रकट होना" },
  "Buy": { base: "buy", past: "bought", pastParticiple: "bought", meaning: "खरीदना" },
  "Wait": { base: "wait", past: "waited", pastParticiple: "waited", meaning: "प्रतीक्षा करना" },
  "Serve": { base: "serve", past: "served", pastParticiple: "served", meaning: "सेवा करना" },
  "Die": { base: "die", past: "died", pastParticiple: "died", meaning: "मरना" },
  "Send": { base: "send", past: "sent", pastParticiple: "sent", meaning: "भेजना" },
  "Expect": { base: "expect", past: "expected", pastParticiple: "expected", meaning: "अपेक्षा करना" },
  "Build": { base: "build", past: "built", pastParticiple: "built", meaning: "बनाना" },
  "Stay": { base: "stay", past: "stayed", pastParticiple: "stayed", meaning: "ठहरना" },
  "Fall": { base: "fall", past: "fell", pastParticiple: "fallen", meaning: "गिरना" },
  "Cut": { base: "cut", past: "cut", pastParticiple: "cut", meaning: "काटना" },
  "Reach": { base: "reach", past: "reached", pastParticiple: "reached", meaning: "पहुंचना" },
  "Kill": { base: "kill", past: "killed", pastParticiple: "killed", meaning: "मारना" },
  "Remain": { base: "remain", past: "remained", pastParticiple: "remained", meaning: "बने रहना" },
  "Suggest": { base: "suggest", past: "suggested", pastParticiple: "suggested", meaning: "सुझाव देना" },
  "Raise": { base: "raise", past: "raised", pastParticiple: "raised", meaning: "उठाना" },
  "Pass": { base: "pass", past: "passed", pastParticiple: "passed", meaning: "पास करना" },
  "Sell": { base: "sell", past: "sold", pastParticiple: "sold", meaning: "बेचना" },
  "Require": { base: "require", past: "required", pastParticiple: "required", meaning: "आवश्यक होना" },
  "Report": { base: "report", past: "reported", pastParticiple: "reported", meaning: "रिपोर्ट करना" },
  "Decide": { base: "decide", past: "decided", pastParticiple: "decided", meaning: "तय करना" },
  "Develop": { base: "develop", past: "developed", pastParticiple: "developed", meaning: "विकसित करना" },
  "Receive": { base: "receive", past: "received", pastParticiple: "received", meaning: "प्राप्त करना" },
  "Agree": { base: "agree", past: "agreed", pastParticiple: "agreed", meaning: "सहमत होना" },
  "Support": { base: "support", past: "supported", pastParticiple: "supported", meaning: "समर्थन करना" },
  "Hit": { base: "hit", past: "hit", pastParticiple: "hit", meaning: "मारना" },
  "Teach": { base: "teach", past: "taught", pastParticiple: "taught", meaning: "सिखाना" },
  "Choose": { base: "choose", past: "chose", pastParticiple: "chosen", meaning: "चुनना" },
  "Discuss": { base: "discuss", past: "discussed", pastParticiple: "discussed", meaning: "चर्चा करना" },
  "Carry": { base: "carry", past: "carried", pastParticiple: "carried", meaning: "ले जाना" },
  "Break": { base: "break", past: "broke", pastParticiple: "broken", meaning: "तोड़ना" },
  "Consider": { base: "consider", past: "considered", pastParticiple: "considered", meaning: "विचार करना" },
  "Continue": { base: "continue", past: "continued", pastParticiple: "continued", meaning: "जारी रखना" },
  "Accept": { base: "accept", past: "accepted", pastParticiple: "accepted", meaning: "स्वीकृत करना" },
  "Discuss": { base: "discuss", past: "discussed", pastParticiple: "discussed", meaning: "चर्चा करना" },
  "Introduce": { base: "introduce", past: "introduced", pastParticiple: "introduced", meaning: "प्रस्तुत करना" },
  "Imagine": { base: "imagine", past: "imagined", pastParticiple: "imagined", meaning: "कल्पना करना" },
  "Avoid": { base: "avoid", past: "avoided", pastParticiple: "avoided", meaning: "बचना" },
  "Explain": { base: "explain", past: "explained", pastParticiple: "explained", meaning: "समझाना" },
  "Hope": { base: "hope", past: "hoped", pastParticiple: "hoped", meaning: "आशा करना" },
  "Achieve": { base: "achieve", past: "achieved", pastParticiple: "achieved", meaning: "प्राप्त करना, पूरा करना, हासिल करना" },
  "Control": { base: "control", past: "controlled", pastParticiple: "controlled", meaning: "नियंत्रण रखना, नियंत्रित करना" },
  "Reach": { base: "reach", past: "reached", pastParticiple: "reached", meaning: "पहुंचना" },
  "Share": { base: "share", past: "shared", pastParticiple: "shared", meaning: "साझा करना" },
  "Agree": { base: "agree", past: "agreed", pastParticiple: "agreed", meaning: "सहमत होना" },
  "Save": { base: "save", past: "saved", pastParticiple: "saved", meaning: "बचाना" },
  "Suggest": { base: "suggest", past: "suggested", pastParticiple: "suggested", meaning: "सुझाव देना, सुझाना" },
  "Protect": { base: "protect", past: "protected", pastParticiple: "protected", meaning: "सुरक्षा करना" },
  "Deal": { base: "deal", past: "dealt", pastParticiple: "dealt", meaning: "निपटना" },
  "Allow": { base: "allow", past: "allowed", pastParticiple: "allowed", meaning: "अनुमति देना" },
  "Wish": { base: "wish", past: "wished", pastParticiple: "wished", meaning: "इच्छा करना" },
  "Plan": { base: "plan", past: "planned", pastParticiple: "planned", meaning: "योजना बनाना" },
  "Apply": { base: "apply", past: "applied", pastParticiple: "applied", meaning: "लागू करना" },
  "Provide": { base: "provide", past: "provided", pastParticiple: "provided", meaning: "देना" },
  "Complain": { base: "complain", past: "complained", pastParticiple: "complained", meaning: "शिकायत करना" },
  "Direct": { base: "direct", past: "directed", pastParticiple: "directed", meaning: "निर्देशित करना" },
  "Organize": { base: "organize", past: "organized", pastParticiple: "organized", meaning: "व्यवस्थित करना" },
  "Refuse": { base: "refuse", past: "refused", pastParticiple: "refused", meaning: "अस्वीकृत करना" },
  "Conduct": { base: "conduct", past: "conducted", pastParticiple: "conducted", meaning: "संचालन करना" },
  "Raise": { base: "raise", past: "raised", pastParticiple: "raised", meaning: "बढ़ाना" },
  "Count": { base: "count", past: "counted", pastParticiple: "counted", meaning: "गिनना" },
  "Reduce": { base: "reduce", past: "reduced", pastParticiple: "reduced", meaning: "घटाना" },
  "Increase": { base: "increase", past: "increased", pastParticiple: "increased", meaning: "बढ़ाना" },
  "Support": { base: "support", past: "supported", pastParticiple: "supported", meaning: "सहायता करना" },
  "Understand": { base: "understand", past: "understood", pastParticiple: "understood", meaning: "समझना" },
  "Describe": { base: "describe", past: "described", pastParticiple: "described", meaning: "वर्णन करना" },
  "Compare": { base: "compare", past: "compared", pastParticiple: "compared", meaning: "तुलना करना" },
  "Focus": { base: "focus", past: "focused", pastParticiple: "focused", meaning: "ध्यान केंद्रित करना" },
  "Determine": { base: "determine", past: "determined", pastParticiple: "determined", meaning: "निर्धारित करना" },
  "Respond": { base: "respond", past: "responded", pastParticiple: "responded", meaning: "प्रतिक्रिया देना" },
  "Modify": { base: "modify", past: "modified", pastParticiple: "modified", meaning: "संशोधित करना" },
  "Combine": { base: "combine", past: "combined", pastParticiple: "combined", meaning: "मिलाना" },
  "Assume": { base: "assume", past: "assumed", pastParticiple: "assumed", meaning: "मान लेना" },
  "Challenge": { base: "challenge", past: "challenged", pastParticiple: "challenged", meaning: "चुनौती देना" },
  "Estimate": { base: "estimate", past: "estimated", pastParticiple: "estimated", meaning: "अनुमान लगाना" },
  "Manage": { base: "manage", past: "managed", pastParticiple: "managed", meaning: "प्रबंधित करना" },
  "Translate": { base: "translate", past: "translated", pastParticiple: "translated", meaning: "अनुवाद करना" },
  "Create": { base: "create", past: "created", pastParticiple: "created", meaning: "निर्माण करना" },
  "Represent": { base: "represent", past: "represented", pastParticiple: "represented", meaning: "प्रतिनिधित्व करना" },
  "Teach": { base: "teach", past: "taught", pastParticiple: "taught", meaning: "सिखाना" },
  "Observe": { base: "observe", past: "observed", pastParticiple: "observed", meaning: "देखना" },
  "Prepare": { base: "prepare", past: "prepared", pastParticiple: "prepared", meaning: "तैयार करना" },
  "Negotiate": { base: "negotiate", past: "negotiated", pastParticiple: "negotiated", meaning: "बातचीत करना" },
  "Improve": { base: "improve", past: "improved", pastParticiple: "improved", meaning: "सुधारना" },
  "Deliver": { base: "deliver", past: "delivered", pastParticiple: "delivered", meaning: "पहुंचाना" },
  "Include": { base: "include", past: "included", pastParticiple: "included", meaning: "समाविष्ट करना" },
  "Clarify": { base: "clarify", past: "clarified", pastParticiple: "clarified", meaning: "स्पष्ट करना" },
  "Summarize": { base: "summarize", past: "summarized", pastParticiple: "summarized", meaning: "संक्षेप में बताना" },
  "Establish": { base: "establish", past: "established", pastParticiple: "established", meaning: "स्थापित करना" },
  "Evaluate": { base: "evaluate", past: "evaluated", pastParticiple: "evaluated", meaning: "मूल्यांकन करना" },
  "Confirm": { base: "confirm", past: "confirmed", pastParticiple: "confirmed", meaning: "पुष्टि करना" },
  "Indicate": { base: "indicate", past: "indicated", pastParticiple: "indicated", meaning: "सूचित करना" },
  "Implement": { base: "implement", past: "implemented", pastParticiple: "implemented", meaning: "कार्यान्वित करना" },
  "Consult": { base: "consult", past: "consulted", pastParticiple: "consulted", meaning: "परामर्श करना" },
  "Address": { base: "address", past: "addressed", pastParticiple: "addressed", meaning: "संबोधित करना" },
  "Allocate": { base: "allocate", past: "allocated", pastParticiple: "allocated", meaning: "आवंटित करना" },
  "Adapt": { base: "adapt", past: "adapted", pastParticiple: "adapted", meaning: "अनुकूलित करना" },
  "Assure": { base: "assure", past: "assured", pastParticiple: "assured", meaning: "आश्वस्त करना" },
  "Analyze": { base: "analyze", past: "analyzed", pastParticiple: "analyzed", meaning: "विश्लेषण करना" },
  "Facilitate": { base: "facilitate", past: "facilitated", pastParticiple: "facilitated", meaning: "सुविधा प्रदान करना" },
  "Specify": { base: "specify", past: "specified", pastParticiple: "specified", meaning: "विशिष्ट करना" },
  "Assess": { base: "assess", past: "assessed", pastParticiple: "assessed", meaning: "मूल्यांकन करना" },
  "Form": { base: "form", past: "formed", pastParticiple: "formed", meaning: "बनाना" },
  "Overcome": { base: "overcome", past: "overcame", pastParticiple: "overcome", meaning: "पार करना" },
  "Review": { base: "review", past: "reviewed", pastParticiple: "reviewed", meaning: "समीक्षा करना, पुनरावलोकन करना" },
  "Acknowledge": { base: "acknowledge", past: "acknowledged", pastParticiple: "acknowledged", meaning: "स्वीकृत करना" },
  "Define": { base: "define", past: "defined", pastParticiple: "defined", meaning: "परिभाषित करना" },
  "Coordinate": { base: "coordinate", past: "coordinated", pastParticiple: "coordinated", meaning: "समन्वयित करना" },
  "Monitor": { base: "monitor", past: "monitored", pastParticiple: "monitored", meaning: "निगरानी करना" },
  "Calculate": { base: "calculate", past: "calculated", pastParticiple: "calculated", meaning: "गणना करना" },
  "Identify": { base: "identify", past: "identified", pastParticiple: "identified", meaning: "पहचानना" },
  "Improve": { base: "improve", past: "improved", pastParticiple: "improved", meaning: "सुधारना" },
  "Obtain": { base: "obtain", past: "obtained", pastParticiple: "obtained", meaning: "प्राप्त करना" },
  "Advance": { base: "advance", past: "advanced", pastParticiple: "advanced", meaning: "उन्नति करना" },
  "Deliver": { base: "deliver", past: "delivered", pastParticiple: "delivered", meaning: "वितरित करना" },
  "Recommend": { base: "recommend", past: "recommended", pastParticiple: "recommended", meaning: "सिफारिश करना" },
  "Maintain": { base: "maintain", past: "maintained", pastParticiple: "maintained", meaning: "बनाए रखना" },
  "Update": { base: "update", past: "updated", pastParticiple: "updated", meaning: "अद्यतन करना" },
  "Simplify": { base: "simplify", past: "simplified", pastParticiple: "simplified", meaning: "सरल बनाना" },
  "Resolve": { base: "resolve", past: "resolved", pastParticiple: "resolved", meaning: "समाधान करना" },
  "Review": { base: "review", past: "reviewed", pastParticiple: "reviewed", meaning: "पुनरावलोकन करना" },
  "Adjust": { base: "adjust", past: "adjusted", pastParticiple: "adjusted", meaning: "समायोजित करना" },
  "Enhance": { base: "enhance", past: "enhanced", pastParticiple: "enhanced", meaning: "बढ़ाना" },
  "Support": { base: "support", past: "supported", pastParticiple: "supported", meaning: "समर्थन करना" },
  "Achieve": { base: "achieve", past: "achieved", pastParticiple: "achieved", meaning: "प्राप्त करना" },
  "Explain": { base: "explain", past: "explained", pastParticiple: "explained", meaning: "समझाना" },
  "Prepare": { base: "prepare", past: "prepared", pastParticiple: "prepared", meaning: "तैयार करना" },
  "Assist": { base: "assist", past: "assisted", pastParticiple: "assisted", meaning: "सहायता करना" },
  "Complete": { base: "complete", past: "completed", pastParticiple: "completed", meaning: "पूरा करना" },
  "Confirm": { base: "confirm", past: "confirmed", pastParticiple: "confirmed", meaning: "पुष्टि करना" },
  "Consider": { base: "consider", past: "considered", pastParticiple: "considered", meaning: "विचार करना" },
  "Determine": { base: "determine", past: "determined", pastParticiple: "determined", meaning: "निर्धारण करना" },
  "Develop": { base: "develop", past: "developed", pastParticiple: "developed", meaning: "विकसित करना" },
  "Establish": { base: "establish", past: "established", pastParticiple: "established", meaning: "स्थापित करना" },
  "Implement": { base: "implement", past: "implemented", pastParticiple: "implemented", meaning: "लागू करना" },
  "Clarify": { base: "clarify", past: "clarified", pastParticiple: "clarified", meaning: "स्पष्ट करना" },
  "Assure": { base: "assure", past: "assured", pastParticiple: "assured", meaning: "आश्वस्त करना" },
  "Allocate": { base: "allocate", past: "allocated", pastParticiple: "allocated", meaning: "आवंटित करना" },
  "Identify": { base: "identify", past: "identified", pastParticiple: "identified", meaning: "पहचानना" },
  "Coordinate": { base: "coordinate", past: "coordinated", pastParticiple: "coordinated", meaning: "समन्वयित करना" },
  "Monitor": { base: "monitor", past: "monitored", pastParticiple: "monitored", meaning: "निगरानी करना" },
  "Calculate": { base: "calculate", past: "calculated", pastParticiple: "calculated", meaning: "गणना करना" },
  "Prioritize": { base: "prioritize", past: "prioritized", pastParticiple: "prioritized", meaning: "प्राथमिकता देना" },
  "Negotiate": { base: "negotiate", past: "negotiated", pastParticiple: "negotiated", meaning: "बातचीत करना" },
  "Advise": { base: "advise", past: "advised", pastParticiple: "advised", meaning: "सलाह देना" },
  "Assess": { base: "assess", past: "assessed", pastParticiple: "assessed", meaning: "मूल्यांकन करना" },
  "Estimate": { base: "estimate", past: "estimated", pastParticiple: "estimated", meaning: "अनुमान लगाना" },
  "Collaborate": { base: "collaborate", past: "collaborated", pastParticiple: "collaborated", meaning: "सहयोग करना" },
  "Generate": { base: "generate", past: "generated", pastParticiple: "generated", meaning: "उत्पन्न करना" },
  "Integrate": { base: "integrate", past: "integrated", pastParticiple: "integrated", meaning: "एकीकृत करना" },
  "Create": { base: "create", past: "created", pastParticiple: "created", meaning: "बनाना" },
  "Sustain": { base: "sustain", past: "sustained", pastParticiple: "sustained", meaning: "बनाए रखना" },
  "Reflect": { base: "reflect", past: "reflected", pastParticiple: "reflected", meaning: "परिलक्षित करना" },
  "Explore": { base: "explore", past: "explored", pastParticiple: "explored", meaning: "अन्वेषण करना" },
  "Summarize": { base: "summarize", past: "summarized", pastParticiple: "summarized", meaning: "संक्षेप में प्रस्तुत करना" },
  "Compile": { base: "compile", past: "compiled", pastParticiple: "compiled", meaning: "संकलित करना" },
  "Propose": { base: "propose", past: "proposed", pastParticiple: "proposed", meaning: "प्रस्तावित करना" },
  "Communicate": { base: "communicate", past: "communicated", pastParticiple: "communicated", meaning: "संवाद करना" },
  "Demonstrate": { base: "demonstrate", past: "demonstrated", pastParticiple: "demonstrated", meaning: "प्रदर्शित करना" },
  "Illustrate": { base: "illustrate", past: "illustrated", pastParticiple: "illustrated", meaning: "उदाहरण देना" },
  "Provide": { base: "provide", past: "provided", pastParticiple: "provided", meaning: "प्रदान करना" },
  "Maintain": { base: "maintain", past: "maintained", pastParticiple: "maintained", meaning: "बनाए रखना" },
  "Arrange": { base: "arrange", past: "arranged", pastParticiple: "arranged", meaning: "व्यवस्था करना" },
  "Authorize": { base: "authorize", past: "authorized", pastParticiple: "authorized", meaning: "अधिकृत करना" },
  "Calculate": { base: "calculate", past: "calculated", pastParticiple: "calculated", meaning: "गणना करना" },
  "Clarify": { base: "clarify", past: "clarified", pastParticiple: "clarified", meaning: "स्पष्ट करना" },
  "Deliver": { base: "deliver", past: "delivered", pastParticiple: "delivered", meaning: "पहुँचाना" },
  "Engage": { base: "engage", past: "engaged", pastParticiple: "engaged", meaning: "संलग्न करना" },
  "Estimate": { base: "estimate", past: "estimated", pastParticiple: "estimated", meaning: "अनुमान लगाना" },
  "Facilitate": { base: "facilitate", past: "facilitated", pastParticiple: "facilitated", meaning: "सुविधा प्रदान करना" },
  "Form": { base: "form", past: "formed", pastParticiple: "formed", meaning: "निर्माण करना" },
  "Highlight": { base: "highlight", past: "highlighted", pastParticiple: "highlighted", meaning: "प्रमुख बनाना" },
  "Incorporate": { base: "incorporate", past: "incorporated", pastParticiple: "incorporated", meaning: "शामिल करना" },
  "Inspect": { base: "inspect", past: "inspected", pastParticiple: "inspected", meaning: "निरीक्षण करना" },
  "Introduce": { base: "introduce", past: "introduced", pastParticiple: "introduced", meaning: "परिचय देना" },
  "Investigate": { base: "investigate", past: "investigated", pastParticiple: "investigated", meaning: "जांचना" },
  "Negotiate": { base: "negotiate", past: "negotiated", pastParticiple: "negotiated", meaning: "बातचीत करना" },
  "Outline": { base: "outline", past: "outlined", pastParticiple: "outlined", meaning: "रूपरेखा बनाना" },
  "Prepare": { base: "prepare", past: "prepared", pastParticiple: "prepared", meaning: "तैयार करना" },
  "Propose": { base: "propose", past: "proposed", pastParticiple: "proposed", meaning: "प्रस्तावित करना" },
  "Publish": { base: "publish", past: "published", pastParticiple: "published", meaning: "प्रकाशित करना" },
  "Recommend": { base: "recommend", past: "recommended", pastParticiple: "recommended", meaning: "सिफारिश करना" },
  "Reinforce": { base: "reinforce", past: "reinforced", pastParticiple: "reinforced", meaning: "मजबूत करना" },
  "Research": { base: "research", past: "researched", pastParticiple: "researched", meaning: "शोध करना" },
  "Resolve": { base: "resolve", past: "resolved", pastParticiple: "resolved", meaning: "हल करना" },
  "Specify": { base: "specify", past: "specified", pastParticiple: "specified", meaning: "निर्दिष्ट करना" },
  "Summarize": { base: "summarize", past: "summarized", pastParticiple: "summarized", meaning: "संक्षेप में प्रस्तुत करना" },
  "Validate": { base: "validate", past: "validated", pastParticiple: "validated", meaning: "प्रमाणित करना" },
  "Verify": { base: "verify", past: "verified", pastParticiple: "verified", meaning: "सत्यापित करना" },
  "Visualize": { base: "visualize", past: "visualized", pastParticiple: "visualized", meaning: "कल्पना करना" },
  "Conclude": { base: "conclude", past: "concluded", pastParticiple: "concluded", meaning: "समाप्त करना" },
  "Debate": { base: "debate", past: "debated", pastParticiple: "debated", meaning: "बहस करना" },
  "Depict": { base: "depict", past: "depicted", pastParticiple: "depicted", meaning: "चित्रित करना" },
  "Document": { base: "document", past: "documented", pastParticiple: "documented", meaning: "दस्तावेज़ बनाना" },
  "Enforce": { base: "enforce", past: "enforced", pastParticiple: "enforced", meaning: "लागू करना" },
  "Evaluate": { base: "evaluate", past: "evaluated", pastParticiple: "evaluated", meaning: "मूल्यांकन करना" },
  "Facilitate": { base: "facilitate", past: "facilitated", pastParticiple: "facilitated", meaning: "सहायता करना" },
  "Forecast": { base: "forecast", past: "forecasted", pastParticiple: "forecasted", meaning: "पूर्वानुमान करना" },
  "Influence": { base: "influence", past: "influenced", pastParticiple: "influenced", meaning: "प्रभाव डालना" },
  "Monitor": { base: "monitor", past: "monitored", pastParticiple: "monitored", meaning: "निगरानी करना" },
  "Operate": { base: "operate", past: "operated", pastParticiple: "operated", meaning: "संचालित करना" },
  "Optimize": { base: "optimize", past: "optimized", pastParticiple: "optimized", meaning: "अनुकूलित करना" },
  "Record": { base: "record", past: "recorded", pastParticiple: "recorded", meaning: "रिकॉर्ड करना" },
  "Regulate": { base: "regulate", past: "regulated", pastParticiple: "regulated", meaning: "नियंत्रित करना" },
  "Streamline": { base: "streamline", past: "streamlined", pastParticiple: "streamlined", meaning: "सुव्यवस्थित करना" },
  "Supervise": { base: "supervise", past: "supervised", pastParticiple: "supervised", meaning: "पर्यवेक्षण करना" },
  "Upgrade": { base: "upgrade", past: "upgraded", pastParticiple: "upgraded", meaning: "उन्नत करना" },
  "Balance": { base: "balance", past: "balanced", pastParticiple: "balanced", meaning: "संतुलित करना" },
  "Collaborate": { base: "collaborate", past: "collaborated", pastParticiple: "collaborated", meaning: "सहयोग करना" },
  "Conserve": { base: "conserve", past: "conserved", pastParticiple: "conserved", meaning: "संरक्षित करना" },
  "Consult": { base: "consult", past: "consulted", pastParticiple: "consulted", meaning: "परामर्श करना" },
  "Delegate": { base: "delegate", past: "delegated", pastParticiple: "delegated", meaning: "सौंपना" },
  "Diagnose": { base: "diagnose", past: "diagnosed", pastParticiple: "diagnosed", meaning: "निदान करना" },
  "Differentiate": { base: "differentiate", past: "differentiated", pastParticiple: "differentiated", meaning: "भेद करना" },
  "Distribute": { base: "distribute", past: "distributed", pastParticiple: "distributed", meaning: "वितरित करना" },
  "Examine": { base: "examine", past: "examined", pastParticiple: "examined", meaning: "परीक्षण करना" },
  "Expand": { base: "expand", past: "expanded", pastParticiple: "expanded", meaning: "फैलाना" },
  "Extract": { base: "extract", past: "extracted", pastParticiple: "extracted", meaning: "निकालना" },
  "Formulate": { base: "formulate", past: "formulated", pastParticiple: "formulated", meaning: "तैयार करना" },
  "Involve": { base: "involve", past: "involved", pastParticiple: "involved", meaning: "शामिल करना" },
  "Preserve": { base: "preserve", past: "preserved", pastParticiple: "preserved", meaning: "संरक्षित करना" },
  "Replicate": { base: "replicate", past: "replicated", pastParticiple: "replicated", meaning: "दोहराना" },
  "Revise": { base: "revise", past: "revised", pastParticiple: "revised", meaning: "संशोधित करना" },
  "Separate": { base: "separate", past: "separated", pastParticiple: "separated", meaning: "अलग करना" },
  "Terminate": { base: "terminate", past: "terminated", pastParticiple: "terminated", meaning: "समाप्त करना" },
  "Utilize": { base: "utilize", past: "utilized", pastParticiple: "utilized", meaning: "उपयोग करना" },
  "Promote": { base: "promote", past: "promoted", pastParticiple: "promoted", meaning: "बढ़ावा देना, प्रोत्साहित करना" },
  "Justify": { base: "justify", past: "justified", pastParticiple: "justified", meaning: "सही ठहराना" },
  "Refine": { base: "refine", past: "refined", pastParticiple: "refined", meaning: "परिष्कृत करना" },
  "Transform": { base: "transform", past: "transformed", pastParticiple: "transformed", meaning: "रूपांतरित करना" },
  "Acquire": { base: "acquire", past: "acquired", pastParticiple: "acquired", meaning: "प्राप्त करना" },
  "Assess": { base: "assess", past: "assessed", pastParticiple: "assessed", meaning: "मूल्यांकन करना" },
  "Capitalize": { base: "capitalize", past: "capitalized", pastParticiple: "capitalized", meaning: "पूंजीकरण करना" },
  "Clarify": { base: "clarify", past: "clarified", pastParticiple: "clarified", meaning: "स्पष्ट करना" },
  "Delegate": { base: "delegate", past: "delegated", pastParticiple: "delegated", meaning: "प्रतिनिधि बनाना" },
  "Facilitate": { base: "facilitate", past: "facilitated", pastParticiple: "facilitated", meaning: "सुगम बनाना" },
  "Integrate": { base: "integrate", past: "integrated", pastParticiple: "integrated", meaning: "एकीकृत करना" },
  "Monitor": { base: "monitor", past: "monitored", pastParticiple: "monitored", meaning: "निगरानी करना" },
  "Prioritize": { base: "prioritize", past: "prioritized", pastParticiple: "prioritized", meaning: "प्राथमिकता देना" },
  "Revise": { base: "revise", past: "revised", pastParticiple: "revised", meaning: "संशोधित करना" },
  "Test": { base: "test", past: "tested", pastParticiple: "tested", meaning: "परीक्षण करना" },
  "Understand": { base: "understand", past: "understood", pastParticiple: "understood", meaning: "समझना" },
  "Adapt": { base: "adapt", past: "adapted", pastParticiple: "adapted", meaning: "अनुकूलित करना" },
  "Design": { base: "design", past: "designed", pastParticiple: "designed", meaning: "डिज़ाइन करना" },
  "Develop": { base: "develop", past: "developed", pastParticiple: "developed", meaning: "विकसित करना" },
  "Implement": { base: "implement", past: "implemented", pastParticiple: "implemented", meaning: "कार्यान्वित करना" },
  "Promote": { base: "promote", past: "promoted", pastParticiple: "promoted", meaning: "बढ़ावा देना" },
  "Validate": { base: "validate", past: "validated", pastParticiple: "validated", meaning: "मान्यता देना" },
  "Verify": { base: "verify", past: "verified", pastParticiple: "verified", meaning: "सत्यापित करना" },
  "Coordinate": { base: "coordinate", past: "coordinated", pastParticiple: "coordinated", meaning: "समन्वयित करना" },
  "Generate": { base: "generate", past: "generated", pastParticiple: "generated", meaning: "उत्पन्न करना" },
  "Review": { base: "review", past: "reviewed", pastParticiple: "reviewed", meaning: "पुनरावलोकन करना" },
  "Summarize": { base: "summarize", past: "summarized", pastParticiple: "summarized", meaning: "संक्षेप में प्रस्तुत करना" },
  "Update": { base: "update", past: "updated", pastParticiple: "updated", meaning: "अद्यतन करना" },
  "Allocate": { base: "allocate", past: "allocated", pastParticiple: "allocated", meaning: "आवंटित करना" },
  "Investigate": { base: "investigate", past: "investigated", pastParticiple: "investigated", meaning: "जांचना" },
  "Operate": { base: "operate", past: "operated", pastParticiple: "operated", meaning: "संचालित करना" },
  "Transform": { base: "transform", past: "transformed", pastParticiple: "transformed", meaning: "परिवर्तित करना" },
  "Articulate": { base: "articulate", past: "articulated", pastParticiple: "articulated", meaning: "स्पष्ट रूप से कहना" },
  "Calculate": { base: "calculate", past: "calculated", pastParticiple: "calculated", meaning: "गणना करना" },
  "Collaborate": { base: "collaborate", past: "collaborated", pastParticiple: "collaborated", meaning: "सहयोग करना" },
  "Conserve": { base: "conserve", past: "conserved", pastParticiple: "conserved", meaning: "संरक्षण करना" },
  "Critique": { base: "critique", past: "critiqued", pastParticiple: "critiqued", meaning: "समीक्षा करना" },
  "Define": { base: "define", past: "defined", pastParticiple: "defined", meaning: "परिभाषित करना" },
  "Describe": { base: "describe", past: "described", pastParticiple: "described", meaning: "वर्णन करना" },
  "Expand": { base: "expand", past: "expanded", pastParticiple: "expanded", meaning: "विस्तार करना" },
  "Extract": { base: "extract", past: "extracted", pastParticiple: "extracted", meaning: "निकालना" },
  "Formulate": { base: "formulate", past: "formulated", pastParticiple: "formulated", meaning: "तैयार करना" },
  "Incorporate": { base: "incorporate", past: "incorporated", pastParticiple: "incorporated", meaning: "समाहित करना" },
  "Inquire": { base: "inquire", past: "inquired", pastParticiple: "inquired", meaning: "पूछताछ करना" },
  "Interpret": { base: "interpret", past: "interpreted", pastParticiple: "interpreted", meaning: "व्याख्या करना" },
  "Manage": { base: "manage", past: "managed", pastParticiple: "managed", meaning: "प्रबंधित करना" },
  "Negotiate": { base: "negotiate", past: "negotiated", pastParticiple: "negotiated", meaning: "वार्ता करना" },
  "Optimize": { base: "optimize", past: "optimized", pastParticiple: "optimized", meaning: "बेहतर बनाना" },
  "Regulate": { base: "regulate", past: "regulated", pastParticiple: "regulated", meaning: "नियंत्रित करना" },
  "Simplify": { base: "simplify", past: "simplified", pastParticiple: "simplified", meaning: "सरल बनाना" },
  "Synthesize": { base: "synthesize", past: "synthesized", pastParticiple: "synthesized", meaning: "संश्लेषण करना" },
  "Visualize": { base: "visualize", past: "visualized", pastParticiple: "visualized", meaning: "कल्पना करना" },
  "Align": { base: "align", past: "aligned", pastParticiple: "aligned", meaning: "संरेखित करना" },
  "Automate": { base: "automate", past: "automated", pastParticiple: "automated", meaning: "स्वचालित करना" },
  "Build": { base: "build", past: "built", pastParticiple: "built", meaning: "निर्माण करना" },
  "Cultivate": { base: "cultivate", past: "cultivated", pastParticiple: "cultivated", meaning: "उगाना" },
  "Evaluate": { base: "evaluate", past: "evaluated", pastParticiple: "evaluated", meaning: "मूल्यांकन करना" },
  "Highlight": { base: "highlight", past: "highlighted", pastParticiple: "highlighted", meaning: "प्रमुख बनाना" },
  "Innovate": { base: "innovate", past: "innovated", pastParticiple: "innovated", meaning: "नवोन्मेष करना" },
  "Leverage": { base: "leverage", past: "leveraged", pastParticiple: "leveraged", meaning: "उपयोग करना" },
  "Prioritize": { base: "prioritize", past: "prioritized", pastParticiple: "prioritized", meaning: "प्राथमिकता देना" },
  "Propose": { base: "propose", past: "proposed", pastParticiple: "proposed", meaning: "प्रस्तावित करना" },
  "Streamline": { base: "streamline", past: "streamlined", pastParticiple: "streamlined", meaning: "सुव्यवस्थित करना" },
  "Translate": { base: "translate", past: "translated", pastParticiple: "translated", meaning: "अनुवाद करना" },
  "Upgrade": { base: "upgrade", past: "upgraded", pastParticiple: "upgraded", meaning: "उन्नत करना" },
  "Utilize": { base: "utilize", past: "utilized", pastParticiple: "utilized", meaning: "उपयोग करना" }
};


  export default verbs;
  
