
// verbs.js

const verbs = {
    "Acquire": { base: "acquire", past: "acquired", pastParticiple: "acquired", meaning: "प्राप्त करना" },
    "Assess": { base: "assess", past: "assessed", pastParticiple: "assessed", meaning: "मूल्यांकन करना" },
    "Capitalize": { base: "capitalize", past: "capitalized", pastParticiple: "capitalized", meaning: "पूंजीकरण करना" },
    "Clarify": { base: "clarify", past: "clarified", pastParticiple: "clarified", meaning: "स्पष्ट करना" },
    "Delegate": { base: "delegate", past: "delegated", pastParticiple: "delegated", meaning: "प्रतिनिधि बनाना" },
    "Facilitate": { base: "facilitate", past: "facilitated", pastParticiple: "facilitated", meaning: "सुगम बनाना" },
    "Integrate": { base: "integrate", past: "integrated", pastParticiple: "integrated", meaning: "एकीकृत करना" },
    "Monitor": { base: "monitor", past: "monitored", pastParticiple: "monitored", meaning: "निगरानी करना" },
    "Prioritize": { base: "prioritize", past: "prioritized", pastParticiple: "prioritized", meaning: "प्राथमिकता देना" },
    "Revise": { base: "revise", past: "revised", pastParticiple: "revised", meaning: "संशोधित करना" },
    "Test": { base: "test", past: "tested", pastParticiple: "tested", meaning: "परीक्षण करना" },
    "Understand": { base: "understand", past: "understood", pastParticiple: "understood", meaning: "समझना" },
    "Adapt": { base: "adapt", past: "adapted", pastParticiple: "adapted", meaning: "अनुकूलित करना" },
    "Design": { base: "design", past: "designed", pastParticiple: "designed", meaning: "डिज़ाइन करना" },
    "Develop": { base: "develop", past: "developed", pastParticiple: "developed", meaning: "विकसित करना" },
    "Implement": { base: "implement", past: "implemented", pastParticiple: "implemented", meaning: "कार्यान्वित करना" },
    "Promote": { base: "promote", past: "promoted", pastParticiple: "promoted", meaning: "बढ़ावा देना" },
    "Validate": { base: "validate", past: "validated", pastParticiple: "validated", meaning: "मान्यता देना" },
    "Verify": { base: "verify", past: "verified", pastParticiple: "verified", meaning: "सत्यापित करना" },
    "Coordinate": { base: "coordinate", past: "coordinated", pastParticiple: "coordinated", meaning: "समन्वयित करना" },
    "Generate": { base: "generate", past: "generated", pastParticiple: "generated", meaning: "उत्पन्न करना" },
    "Review": { base: "review", past: "reviewed", pastParticiple: "reviewed", meaning: "पुनरावलोकन करना" },
    "Summarize": { base: "summarize", past: "summarized", pastParticiple: "summarized", meaning: "संक्षेप में प्रस्तुत करना" },
    "Update": { base: "update", past: "updated", pastParticiple: "updated", meaning: "अद्यतन करना" },
    "Allocate": { base: "allocate", past: "allocated", pastParticiple: "allocated", meaning: "आवंटित करना" },
    "Investigate": { base: "investigate", past: "investigated", pastParticiple: "investigated", meaning: "जांचना" },
    "Operate": { base: "operate", past: "operated", pastParticiple: "operated", meaning: "संचालित करना" },
    "Transform": { base: "transform", past: "transformed", pastParticiple: "transformed", meaning: "परिवर्तित करना" },
    "Articulate": { base: "articulate", past: "articulated", pastParticiple: "articulated", meaning: "स्पष्ट रूप से कहना" },
    "Calculate": { base: "calculate", past: "calculated", pastParticiple: "calculated", meaning: "गणना करना" },
    "Collaborate": { base: "collaborate", past: "collaborated", pastParticiple: "collaborated", meaning: "सहयोग करना" },

    "Integrate": { base: "integrate", past: "integrated", pastParticiple: "integrated", meaning: "एकीकृत करना" },
    "Monitor": { base: "monitor", past: "monitored", pastParticiple: "monitored", meaning: "निगरानी करना" },
    "Prioritize": { base: "prioritize", past: "prioritized", pastParticiple: "prioritized", meaning: "प्राथमिकता देना" },
    "Revise": { base: "revise", past: "revised", pastParticiple: "revised", meaning: "संशोधित करना" },
    "Test": { base: "test", past: "tested", pastParticiple: "tested", meaning: "परीक्षण करना" },
    "Understand": { base: "understand", past: "understood", pastParticiple: "understood", meaning: "समझना" },
    "Adapt": { base: "adapt", past: "adapted", pastParticiple: "adapted", meaning: "अनुकूलित करना" },
    "Design": { base: "design", past: "designed", pastParticiple: "designed", meaning: "डिज़ाइन करना" },
    "Develop": { base: "develop", past: "developed", pastParticiple: "developed", meaning: "विकसित करना" },
    "Implement": { base: "implement", past: "implemented", pastParticiple: "implemented", meaning: "कार्यान्वित करना" },
    "Promote": { base: "promote", past: "promoted", pastParticiple: "promoted", meaning: "बढ़ावा देना" },
    "Validate": { base: "validate", past: "validated", pastParticiple: "validated", meaning: "मान्यता देना" },
    "Verify": { base: "verify", past: "verified", pastParticiple: "verified", meaning: "सत्यापित करना" },
    "Coordinate": { base: "coordinate", past: "coordinated", pastParticiple: "coordinated", meaning: "समन्वयित करना" },
    "Generate": { base: "generate", past: "generated", pastParticiple: "generated", meaning: "उत्पन्न करना" },
    "Review": { base: "review", past: "reviewed", pastParticiple: "reviewed", meaning: "पुनरावलोकन करना" },
    "Summarize": { base: "summarize", past: "summarized", pastParticiple: "summarized", meaning: "संक्षेप में प्रस्तुत करना" },
    "Update": { base: "update", past: "updated", pastParticiple: "updated", meaning: "अद्यतन करना" },
    "Allocate": { base: "allocate", past: "allocated", pastParticiple: "allocated", meaning: "आवंटित करना" },
    "Investigate": { base: "investigate", past: "investigated", pastParticiple: "investigated", meaning: "जांचना" },
    "Operate": { base: "operate", past: "operated", pastParticiple: "operated", meaning: "संचालित करना" },
    "Transform": { base: "transform", past: "transformed", pastParticiple: "transformed", meaning: "परिवर्तित करना" },
    "Articulate": { base: "articulate", past: "articulated", pastParticiple: "articulated", meaning: "स्पष्ट रूप से कहना" },
    "Calculate": { base: "calculate", past: "calculated", pastParticiple: "calculated", meaning: "गणना करना" },
    "Collaborate": { base: "collaborate", past: "collaborated", pastParticiple: "collaborated", meaning: "सहयोग करना" },

    "Integrate": { base: "integrate", past: "integrated", pastParticiple: "integrated", meaning: "एकीकृत करना" },
    "Monitor": { base: "monitor", past: "monitored", pastParticiple: "monitored", meaning: "निगरानी करना" },
    "Prioritize": { base: "prioritize", past: "prioritized", pastParticiple: "prioritized", meaning: "प्राथमिकता देना" },
    "Revise": { base: "revise", past: "revised", pastParticiple: "revised", meaning: "संशोधित करना" },
    "Test": { base: "test", past: "tested", pastParticiple: "tested", meaning: "परीक्षण करना" },
    "Understand": { base: "understand", past: "understood", pastParticiple: "understood", meaning: "समझना" },
    "Adapt": { base: "adapt", past: "adapted", pastParticiple: "adapted", meaning: "अनुकूलित करना" },
    "Design": { base: "design", past: "designed", pastParticiple: "designed", meaning: "डिज़ाइन करना" },
    "Develop": { base: "develop", past: "developed", pastParticiple: "developed", meaning: "विकसित करना" },
    "Implement": { base: "implement", past: "implemented", pastParticiple: "implemented", meaning: "कार्यान्वित करना" },
    "Promote": { base: "promote", past: "promoted", pastParticiple: "promoted", meaning: "बढ़ावा देना" },
    "Validate": { base: "validate", past: "validated", pastParticiple: "validated", meaning: "मान्यता देना" },
    "Verify": { base: "verify", past: "verified", pastParticiple: "verified", meaning: "सत्यापित करना" },
    "Coordinate": { base: "coordinate", past: "coordinated", pastParticiple: "coordinated", meaning: "समन्वयित करना" },
    "Generate": { base: "generate", past: "generated", pastParticiple: "generated", meaning: "उत्पन्न करना" },
    "Review": { base: "review", past: "reviewed", pastParticiple: "reviewed", meaning: "पुनरावलोकन करना" },
    "Summarize": { base: "summarize", past: "summarized", pastParticiple: "summarized", meaning: "संक्षेप में प्रस्तुत करना" },
    "Update": { base: "update", past: "updated", pastParticiple: "updated", meaning: "अद्यतन करना" },
    "Allocate": { base: "allocate", past: "allocated", pastParticiple: "allocated", meaning: "आवंटित करना" },
    "Investigate": { base: "investigate", past: "investigated", pastParticiple: "investigated", meaning: "जांचना" },
    "Operate": { base: "operate", past: "operated", pastParticiple: "operated", meaning: "संचालित करना" },
    "Transform": { base: "transform", past: "transformed", pastParticiple: "transformed", meaning: "परिवर्तित करना" },
    "Articulate": { base: "articulate", past: "articulated", pastParticiple: "articulated", meaning: "स्पष्ट रूप से कहना" },
    "Calculate": { base: "calculate", past: "calculated", pastParticiple: "calculated", meaning: "गणना करना" },
    "Collaborate": { base: "collaborate", past: "collaborated", pastParticiple: "collaborated", meaning: "सहयोग करना" },  
    "Conserve": { base: "conserve", past: "conserved", pastParticiple: "conserved", meaning: "संरक्षण करना" },
    "Critique": { base: "critique", past: "critiqued", pastParticiple: "critiqued", meaning: "समीक्षा करना" },
    "Describe": { base: "describe", past: "described", pastParticiple: "described", meaning: "वर्णन करना" },
    "Expand": { base: "expand", past: "expanded", pastParticiple: "expanded", meaning: "विस्तार करना" },
    "Extract": { base: "extract", past: "extracted", pastParticiple: "extracted", meaning: "निकालना" },
    "Formulate": { base: "formulate", past: "formulated", pastParticiple: "formulated", meaning: "तैयार करना" },
    "Incorporate": { base: "incorporate", past: "incorporated", pastParticiple: "incorporated", meaning: "समाहित करना" },
    "Inquire": { base: "inquire", past: "inquired", pastParticiple: "inquired", meaning: "पूछताछ करना" },
    "Interpret": { base: "interpret", past: "interpreted", pastParticiple: "interpreted", meaning: "व्याख्या करना" },
    "Manage": { base: "manage", past: "managed", pastParticiple: "managed", meaning: "प्रबंधित करना" },
    "Negotiate": { base: "negotiate", past: "negotiated", pastParticiple: "negotiated", meaning: "वार्ता करना" },
    "Optimize": { base: "optimize", past: "optimized", pastParticiple: "optimized", meaning: "बेहतर बनाना" },
    "Regulate": { base: "regulate", past: "regulated", pastParticiple: "regulated", meaning: "नियंत्रित करना" },
    "Simplify": { base: "simplify", past: "simplified", pastParticiple: "simplified", meaning: "सरल बनाना" },
    "Synthesize": { base: "synthesize", past: "synthesized", pastParticiple: "synthesized", meaning: "संश्लेषण करना" },
    "Visualize": { base: "visualize", past: "visualized", pastParticiple: "visualized", meaning: "कल्पना करना" },
    "Align": { base: "align", past: "aligned", pastParticiple: "aligned", meaning: "संरेखित करना" },
    "Automate": { base: "automate", past: "automated", pastParticiple: "automated", meaning: "स्वचालित करना" },
    "Build": { base: "build", past: "built", pastParticiple: "built", meaning: "निर्माण करना" },
    "Cultivate": { base: "cultivate", past: "cultivated", pastParticiple: "cultivated", meaning: "उगाना" },
    "Evaluate": { base: "evaluate", past: "evaluated", pastParticiple: "evaluated", meaning: "मूल्यांकन करना" },
    "Highlight": { base: "highlight", past: "highlighted", pastParticiple: "highlighted", meaning: "प्रमुख बनाना" },
    "Innovate": { base: "innovate", past: "innovated", pastParticiple: "innovated", meaning: "नवोन्मेष करना" },
    "Leverage": { base: "leverage", past: "leveraged", pastParticiple: "leveraged", meaning: "उपयोग करना" },
    "Prioritize": { base: "prioritize", past: "prioritized", pastParticiple: "prioritized", meaning: "प्राथमिकता देना" },
    "Summarize": { base: "summarize", past: "summarized", pastParticiple: "summarized", meaning: "संक्षेप में प्रस्तुत करना" },
    "Upgrade": { base: "upgrade", past: "upgraded", pastParticiple: "upgraded", meaning: "उन्नत करना" },
    "Utilize": { base: "utilize", past: "utilized", pastParticiple: "utilized", meaning: "उपयोग करना" }
  };
  
  export default verbs;
  